// Code generated by timoni.
// Note that this file must have no imports and all values must be concrete.

@if(!debug)

package main

// Defaults
values: {
	image: {
		repository: "ghcr.io/open-telemetry/opentelemetry-operator/opentelemetry-operator"
		digest:     ""
		tag:        "0.95.0"
	}
	kubeRBACProxy: image: {
		repository: "gcr.io/kubebuilder/kube-rbac-proxy"
		digest:     ""
		tag:        "v0.13.1"
	}
}
