name: Release module
on:
  push:
    tag: ['flipt/*'] # semver format

permissions:
  contents: read # needed for checkout
  packages: write # needed for GHCR access

jobs:
  push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup Timoni
        uses: stefanprodan/timoni/actions/setup@main
      - name: Vet module
        run: |
          timoni mod vet ./flipt
      - name: Push module
        run: |
          VERSION=$(echo "${{ github.ref_name }}" | sed '/flipt\/[v]\?/!{q100}; {s#flipt/[v]\?##}' || (echo "unexpected tag version" && exit 1))
          timoni mod push ./flipt \
            oci://ghcr.io/${{ github.repository_owner }}/timoni-flipt \
            --version $VERSION \
            --creds ${{ github.actor }}:${{ secrets.GITHUB_TOKEN }}
